name: scheduling
description: A new project.
publish_to: 'none'
version: 0.0.0+0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  sembast: ^3.3.1
  path_provider: ^2.0.11
  encrypt: ^5.0.1
  crypto: ^3.0.2

  provider: ^6.0.4
  uuid: ^3.0.7

  http: ^0.13.5
  html: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
